name: pokemon_app
description: "Project Pokemon App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get_it:
  dio:
  rxdart:
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  flutter_svg: ^1.0.3
  dartz:
  cached_network_image: ^3.2.3
  sqflite: ^2.4.1
  path: ^1.8.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/